TECHNOLOGIES = [
    "PYTHON",
    "typescript"
    "SQL",
    "next",
    "strawberry",
    "apollo",
    "render",
    "vercel",
    "sentry",
    "Jmeter",
    "Grafana",
    "Prometheus",
    "networking",
    "azure",
    "Grafana K6",
    "HTTP",
    "HTTPS",
    "TCP/UDP",
    "LoadRunner",
    "RESTful",
    "REST",
    "rainforestQA",
    "PostgreSQL"
    "NOSQL",
    "DOCKER",
    "NUMPY",
    "FLASK-RESTFUL",
    "REST",
    "FAST",
    "WEBSOCKET",
    "MYSQL",
    "OOP",
    "POSTMAN",
    "MONGODB",
    "FLASK",
    "VUE.JS",
    "AWS",
    "GIT",
    "TENSORFLOW",
    "Scrum",
    "SELENIUM",
    "BITBUCKET",
    "FASTAPI",
    "PYTORCH",
    "DJANGO",
    "VAGRANT",
    "FLASK REST",
    "JENKINS",
    "AIRFLOW",
    "RabbitMQ",
    "AMQP",
    "XMPP",
    "MQTT",
    "Gerrit",
    "SQLALCHEMY",
    "JAVASCRIPT",
    "GCP",
    "HTML",
    "GITLAB",
    "LINUX",
    "ANGULAR",
    "REACT",
    "CSS",
    "GITHUB",
    "SPLUNK",
    "JEST",
    "PANDAS",
    "TRAVIS CI",
    "TORNADO",
    "CELERY",
    "POSTGRES",
    "MICROSOFT AZURE",
    "GRAPHQL",
    "PYTEST",
    "SPLINTER",
    "JUNIT",
    "SPLINTER 3",
    "JAS",
    "KOTLIN",
    "JASMINE",
    "JAVA",
    "SWAGGER",
    "DJANGO REST",
    "KUBERNETES",
    "OAUTH",
    "CHAI",
    "EXPRESS",
    "ANDROID",
    "KNOCKOUT",
    "AGILE",
    "MSSQL",
    "RUBY",
    "MOCHA",
    "SOAP",
    "VB.NET",
    "DRF",
    "DRUPAL",
    "ASP",
    "C",
    "GROOVY",
    "APACHE KAFKA",
    "SYMFONY",
    "RUST",
    "JDBC",
    "AGILE METHODOLOGY",
    "PERL",
    "REDIS",
    "ECR",
    "Helm",
    "ELASTICSEARCH",
    "JAVA DEVELOPER",
    "C#",
    "NO SQL",
    "HADOOP",
    "SCALA",
    "GOLANG",
    "XAMARIN",
    "BABEL",
    "VUEJS",
    "LARAVEL",
    "HUGO",
    "GATLING",
    "LINUX ADMINISTRATOR",
    "DOCKER CONTAINER",
    "DOCKER CONTAINERS",
    "WEB API",
    "K8S",
    "K8",
    "MICROSERVICES",
    "GIT HUB",
    "POSTGRES SQL",
    "MICROSOFT AZURE KUBERNETES",
    "MOBILE APP",
    "MOBILE APP DEVELOPMENT",
    "JENKINS PIPELINE",
    "JENKINS CI/CD",
    "UNIT TEST",
    "API TEST",
    "PERFORMANCE TEST",
    "TEST ENGINEER",
    "ECS",
    "SECURITY TEST",
    "LOAD TEST",
    "FUNCTIONAL TEST",
    "TEST AUTOMATION",
    "QA TEST",
    "QUALITY ASSURANCE TEST",
    "DEVELOPER TEST",
    "DEVOPS TEST",
    "SYSTEM TEST",
    "WHITE BOX TEST",
    "BLACK BOX TEST",
    "AUTOMATED TEST",
    "UI TEST",
    "TEST SCRIPT",
    "TEST CASE",
    "TEST PLAN",
    "TEST STRATEGY",
    "AUTOMATED TESTING",
    "QUALITY ASSURANCE TESTING",
    "QA TESTING",
    "SOFTWARE TESTING",
    "TEST MANAGEMENT",
    "TEST DESIGN",
    "TEST EXECUTION",
    "TEST REPORTING",
    "TEST ANALYSIS",
    "TEST STRATEGY",
    "TEST ARCHITECTURE",
    "TEST FRAMEWORK",
    "TEST METHODOLOGY",
    "TEST PLAN",
    "TEST DATA",
    "TEST ENVIRONMENT",
    "TEST SUITE",
    "TEST SCRIPT",
    "CI/CD",
]
